language: php
dist: trusty
sudo: false

branches:
  only:
    - master

matrix:
  include:
    - php: 7.3
      env: 'DEPENDENCIES=highest'
    - php: 7.2
    - php: 7.2
      env: 'SCENARIO=drush8'
    - php: 7.1
      env: 'SCENARIO=drush8'
    - php: 7.0
      env: 'SCENARIO=phpunit4'
    - php: 5.6
      env: 'SCENARIO=phpunit4'
    - php: 5.6
      env: 'SCENARIO=phpunit4 DEPENDENCIES=lowest'

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

before_install:
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]]; then export COMPOSER_MEMORY_LIMIT=-1; fi;
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'
  - composer drupal:scaffold

script:
  - composer test
